# Embedding/Images Worker
name = "sniffr-images-worker"
main = "workers/images-worker.js"
compatibility_date = "2025-06-19"
account_id = "774b68e8a6ad8edd33820cd760f785d9"

[[vectorize]]
binding = "VECTORIZE"
index_name = "sniffr-dog-images"

[ai]
binding = "AI"

# -----------------------------
# Caption Worker
[[services]]
name = "sniffr-caption-worker"
main = "workers/caption-worker.js"
compatibility_date = "2025-06-19"
account_id = "774b68e8a6ad8edd33820cd760f785d9"

# -----------------------------
# Tag Worker
[[services]]
name = "sniffr-tag-worker"
main = "workers/tags-worker.js"
compatibility_date = "2025-06-19"
account_id = "774b68e8a6ad8edd33820cd760f785d9"
