name = "sniffr-personality-worker"
main = "personality-worker.js"
compatibility_date = "2024-06-28"
vectorize = [
  { binding = "VECTORIZE_TEXT", index_name = "sniffr-chat-embeddings" }
]

[[d1_databases]]
binding = "DB"
database_name = "sniffr-db"
database_id = "3bfee506-815a-4249-bf4f-95886e459234"
